c-rack/cbor-java

- src/main/java/co/nstant/in/cbor/model/Array.java
> Solution: add construtor to support setting initial capacity

- pom.xml
Solution: update maven-surefire-report-plugin to 2.19.1
> Problem: maven-surefire-report-plugin is outdated

- pom.xml
Solution: update to latest versions
> Problem: several dependencies are outdated

- pom.xml
Solution: update to latest version
> Problem: maven-project-info-reports-plugin is outdated

- src/main/java/co/nstant/in/cbor/CborDecoder.java
- src/main/java/co/nstant/in/cbor/model/AbstractFloat.java
- src/main/java/co/nstant/in/cbor/model/ChunkableDataItem.java
- src/main/java/co/nstant/in/cbor/model/DataItem.java
- src/main/java/co/nstant/in/cbor/model/DoublePrecisionFloat.java
- src/main/java/co/nstant/in/cbor/model/SimpleValue.java
- src/main/java/co/nstant/in/cbor/model/Special.java
- src/main/java/co/nstant/in/cbor/model/Tag.java
> Problem: PMD complains about unnecessary parentheses

- pom.xml
Solution: update them to latest versions
> Problem: some dependencies are out of date

- pom.xml
Solution: update to version 4.3.0
> Problem: coveralls-maven-plugin is outdated

- pom.xml
Solution: update to latest version
> Problem: depdendencies are out of date

- pom.xml
Solution: update jacoco-maven-plugin to 0.7.9
> Problem: jacoco-maven-plugin is outdated

- pom.xml
Solution: update pmd and surefire plugins
> Problem: some deps are out of date

- src/main/java/co/nstant/in/cbor/decoder/UnicodeStringDecoder.java
Solution: use ByteArrayOutputStream.write(byte[], int, int)
> Problem: no need to check for IOException

- pom.xml
> Problem: deps are out of date

- src/main/java/co/nstant/in/cbor/decoder/UnicodeStringDecoder.java
- src/main/java/co/nstant/in/cbor/encoder/UnicodeStringEncoder.java
- src/main/java/co/nstant/in/cbor/model/Array.java
Solution: use Charset instead of String
> Problem: UnsupportedEncodingException

- pom.xml
Solution: update them to latest version
> Problem: some dependencies are outdated

- src/main/java/co/nstant/in/cbor/decoder/ByteStringDecoder.java
- src/main/java/co/nstant/in/cbor/decoder/MapDecoder.java
- src/main/java/co/nstant/in/cbor/decoder/UnicodeStringDecoder.java
- src/test/java/co/nstant/in/cbor/decoder/ArrayDecoderTest.java
- src/test/java/co/nstant/in/cbor/decoder/ByteStringDecoderTest.java
- src/test/java/co/nstant/in/cbor/decoder/CborDecoderTest.java
- src/test/java/co/nstant/in/cbor/decoder/MapDecoderTest.java
- src/test/java/co/nstant/in/cbor/decoder/UnicodeStringDecoderTest.java
Problem: null checks forgotten to check for the end of the stream
Solution: insert null checks & add tests
> Fix #49, Add missing null checks

- src/main/java/co/nstant/in/cbor/builder/MapBuilder.java
- src/test/java/co/nstant/in/cbor/builder/MapBuilderTest.java
Solution: add startMap(...) functions
> Problem: MapBuilder can't add infinite length map

- src/main/java/co/nstant/in/cbor/CborDecoder.java
- src/test/java/co/nstant/in/cbor/decoder/CborDecoderTest.java
Solution: While decoding and setting a tag, iterate
until the outermost subtag is found and apply
the tag to that, not the item itself.
> Problem: A Tagged tag is not decoded correctly

- README.md
- pom.xml
> Release version 0.8

- pom.xml
> Problem: no deps for maven relase

- pom.xml
> Problem: maven-javadoc-plugin is outdated

- src/main/java/co/nstant/in/cbor/CborBuilder.java
- src/main/java/co/nstant/in/cbor/CborEncoder.java
- src/main/java/co/nstant/in/cbor/builder/ArrayBuilder.java
- src/main/java/co/nstant/in/cbor/builder/MapBuilder.java
- src/main/java/co/nstant/in/cbor/builder/MapEntryBuilder.java
- src/main/java/co/nstant/in/cbor/model/Array.java
- src/main/java/co/nstant/in/cbor/model/DataItem.java
- src/test/java/co/nstant/in/cbor/builder/MapBuilderTest.java
- src/test/java/co/nstant/in/cbor/examples/Example83Test.java
> Add support for fluent tagging, with nested tags.
